### ISSUE TITLE
Workgroup variables permitted only for compute shader, not vertex  or fragment

### ISSUE THREAD

**Issue by dneto0** [gpuweb/spirv-execution-env#39]

**Comment by zoddicus** [comment]
Things that need to be commented on/updated:
- WorkgroupMemory specific semantic bits shouldn't be allowed for non-Workgroup situations
- OpControllBarrier* and OpMemoryBarrier* are implicitly Compute only due to this requirement
- Workgroup variables are declared in the global scope, it is the pointer accesses that are limited to Compute shaders
